services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: one_health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  servico_analise:
    build:
      context: .
      dockerfile: ServicoAnalise.Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/one_health
    ports:
      - "50052:50052"
    depends_on:
      - postgres
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    environment:
      DB_CONNECTION_STRING: Host=postgres;Database=one_health;Username=postgres;Password=postgres
      ANALISE_URL: http://servico_analise:50052
    ports:
      - "8080:8080"
      - "14000:14000"
      - "14001:14001"
    depends_on:
      - postgres
      - servico_analise
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Frontend.Dockerfile
      args:
        VITE_API_BASE_URL: http://PC3_IP:8080
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data:
