# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: limpeza.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'limpeza.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlimpeza.proto\x12\x11pre_processamento\"S\n\tDadoBruto\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0c\n\x04zona\x18\x02 \x01(\t\x12\x11\n\ttipo_dado\x18\x03 \x01(\t\x12\x12\n\nvalor_sujo\x18\x04 \x01(\t\"[\n\tDadoLimpo\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\x12\x13\n\x0bvalor_limpo\x18\x03 \x01(\x01\x12\x15\n\rmensagem_erro\x18\x04 \x01(\t\"?\n\x10\x42locoDadosBrutos\x12+\n\x05\x64\x61\x64os\x18\x01 \x03(\x0b\x32\x1c.pre_processamento.DadoBruto\"?\n\x10\x42locoDadosLimpos\x12+\n\x05\x64\x61\x64os\x18\x01 \x03(\x0b\x32\x1c.pre_processamento.DadoLimpo2l\n\x0cLimpezaDados\x12\\\n\x10UniformizarBloco\x12#.pre_processamento.BlocoDadosBrutos\x1a#.pre_processamento.BlocoDadosLimposB\x17\xaa\x02\x14Gateway.GrpcServicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'limpeza_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\024Gateway.GrpcServices'
  _globals['_DADOBRUTO']._serialized_start=36
  _globals['_DADOBRUTO']._serialized_end=119
  _globals['_DADOLIMPO']._serialized_start=121
  _globals['_DADOLIMPO']._serialized_end=212
  _globals['_BLOCODADOSBRUTOS']._serialized_start=214
  _globals['_BLOCODADOSBRUTOS']._serialized_end=277
  _globals['_BLOCODADOSLIMPOS']._serialized_start=279
  _globals['_BLOCODADOSLIMPOS']._serialized_end=342
  _globals['_LIMPEZADADOS']._serialized_start=344
  _globals['_LIMPEZADADOS']._serialized_end=452
# @@protoc_insertion_point(module_scope)
