# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analysis_pb2 as analysis__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analysis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnaliseServiceStub(object):
    """Invocado pelo Servidor para análise estatística e deteção de padrões.
    O serviço corre em Python com pandas/numpy/scipy.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalisarZona = channel.unary_unary(
                '/analysis.AnaliseService/AnalisarZona',
                request_serializer=analysis__pb2.PedidoAnalise.SerializeToString,
                response_deserializer=analysis__pb2.ResultadoAnalise.FromString,
                _registered_method=True)
        self.DetectarPadroes = channel.unary_unary(
                '/analysis.AnaliseService/DetectarPadroes',
                request_serializer=analysis__pb2.PedidoAnalise.SerializeToString,
                response_deserializer=analysis__pb2.ResultadoPadroes.FromString,
                _registered_method=True)
        self.PreviRisco = channel.unary_unary(
                '/analysis.AnaliseService/PreviRisco',
                request_serializer=analysis__pb2.PedidoPrevisao.SerializeToString,
                response_deserializer=analysis__pb2.ResultadoPrevisao.FromString,
                _registered_method=True)
        self.AvaliarAlarmesHistoricos = channel.unary_unary(
                '/analysis.AnaliseService/AvaliarAlarmesHistoricos',
                request_serializer=analysis__pb2.RequestAvaliacao.SerializeToString,
                response_deserializer=analysis__pb2.ResultadoAvaliacao.FromString,
                _registered_method=True)


class AnaliseServiceServicer(object):
    """Invocado pelo Servidor para análise estatística e deteção de padrões.
    O serviço corre em Python com pandas/numpy/scipy.
    """

    def AnalisarZona(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectarPadroes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviRisco(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AvaliarAlarmesHistoricos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnaliseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalisarZona': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalisarZona,
                    request_deserializer=analysis__pb2.PedidoAnalise.FromString,
                    response_serializer=analysis__pb2.ResultadoAnalise.SerializeToString,
            ),
            'DetectarPadroes': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectarPadroes,
                    request_deserializer=analysis__pb2.PedidoAnalise.FromString,
                    response_serializer=analysis__pb2.ResultadoPadroes.SerializeToString,
            ),
            'PreviRisco': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviRisco,
                    request_deserializer=analysis__pb2.PedidoPrevisao.FromString,
                    response_serializer=analysis__pb2.ResultadoPrevisao.SerializeToString,
            ),
            'AvaliarAlarmesHistoricos': grpc.unary_unary_rpc_method_handler(
                    servicer.AvaliarAlarmesHistoricos,
                    request_deserializer=analysis__pb2.RequestAvaliacao.FromString,
                    response_serializer=analysis__pb2.ResultadoAvaliacao.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analysis.AnaliseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analysis.AnaliseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnaliseService(object):
    """Invocado pelo Servidor para análise estatística e deteção de padrões.
    O serviço corre em Python com pandas/numpy/scipy.
    """

    @staticmethod
    def AnalisarZona(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnaliseService/AnalisarZona',
            analysis__pb2.PedidoAnalise.SerializeToString,
            analysis__pb2.ResultadoAnalise.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectarPadroes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnaliseService/DetectarPadroes',
            analysis__pb2.PedidoAnalise.SerializeToString,
            analysis__pb2.ResultadoPadroes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviRisco(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnaliseService/PreviRisco',
            analysis__pb2.PedidoPrevisao.SerializeToString,
            analysis__pb2.ResultadoPrevisao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AvaliarAlarmesHistoricos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analysis.AnaliseService/AvaliarAlarmesHistoricos',
            analysis__pb2.RequestAvaliacao.SerializeToString,
            analysis__pb2.ResultadoAvaliacao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
